name: Build Workflow

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The name of the artifact to upload'
        required: false
        type: string
      create_zip:
        description: 'Se impostato a true, genera lo zip'
        required: false
        type: boolean
        default: false
      paths:
        description: 'Files or folders to exclude from the artifact'
        required: false
        type: string
        default: |
          !.git
          !.github
          !node_modules
jobs:
  build:
    name: Create Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: 'package.json'
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@writepoetry'

      - name: Install NPM Dependencies
        if: hashFiles('package.json') != ''
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: npm run build --if-present

      - name: Install Composer Dependencies
        if: hashFiles('composer.json') != ''
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare Zip Asset
        id: zip
        if: ${{ inputs.create_zip }}
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          VERSION="${GITHUB_REF_NAME#v}"
          
          npm run plugin-zip
          
          mv "$PACKAGE_NAME"{.zip,"-$VERSION.zip"}
          echo "zip_file=$PACKAGE_NAME-$VERSION.zip" >> $GITHUB_OUTPUT
        # working-directory: ${{ github.workspace }}

      - name: Upload Build Artifact
        if: ${{ inputs.artifact_name != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            ./
            ${{ inputs.paths }}
          retention-days: 1

      - name: Upload Zip Artifact
        if: ${{ inputs.create_zip }}
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: ./*.zip
          if-no-files-found: error
          retention-days: 1