name: Reusable PHP/WordPress Tests

on:
  workflow_call:
    inputs:
      php_versions:
        description: "List of PHP versions for the test matrix"
        required: false
        type: string
        default: "['7.4', '8.0', '8.1', '8.2']"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ${{ fromJson(inputs.php_versions) }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v5

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mysqli
          coverage: none

      - run: composer install --no-interaction --prefer-dist

      - name: Prepare WordPress test suite
        run: |
          mysql -u root -proot -h 127.0.0.1 -e 'DROP DATABASE IF EXISTS wordpress_test; CREATE DATABASE wordpress_test;'
          rm -rf /tmp/wordpress-tests-lib /tmp/wordpress
          SKIP_DB_CREATE=true bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

      - name: Run PHPCS
        run: |
          composer global require wp-coding-standards/wpcs
          phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
          phpcs

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit
          WP_MULTISITE=1 vendor/bin/phpunit
